### ISSUE TITLE
Installing the layout without admin permission

### ISSUE THREAD

**Issue by AndreaCallia** [ilpianista/itlinux-win-keyboard#1]
Dear @ilpianista ,

is it possible to install or load/import the layout without admin permission? I am working in London and sometimes I need to use common workstations with Windows installed where I cannot be admin but just normal user.

Many thanks for this precious tool...

**Comment by ilpianista** [comment]
Hi,
it looks like you need [PKL](https://sourceforge.net/projects/pkl/). It provides a [klc2ini](https://sourceforge.net/p/pkl/code/HEAD/tree/trunk/utilities/klc2ini.pl) Perl script to convert a MSKLC layout to PKL format.

Unfortunately, I don't have a Windows machine to test right now. Please try it and let us know!
